# Generated by Django 2.1.2 on 2018-10-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcontent', models.TextField(max_length=200)),
                ('blevel', models.IntegerField()),
                ('bsolution', models.TextField(max_length=200)),
                ('bresult', models.TextField(max_length=50)),
                ('bman', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtitle', models.CharField(max_length=200)),
                ('vtrader_code', models.CharField(max_length=20)),
                ('vcommit_date', models.DateField()),
                ('vname', models.CharField(max_length=100)),
                ('visdebug', models.BooleanField()),
                ('vserver_ip', models.CharField(max_length=100)),
                ('vsvn_version', models.CharField(max_length=20)),
                ('vupdate_address', models.CharField(max_length=100)),
                ('vversion_code', models.CharField(max_length=20)),
                ('vupadete_version', models.CharField(max_length=200)),
                ('vbundle_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='buginfo',
            name='bversioninfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VersionInfoApp.VersionInfo'),
        ),
    ]
